# Generated by Django 3.2.8 on 2021-10-22 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('hospitalNumber', models.TextField()),
                ('nationalNumber', models.TextField()),
                ('communicationMethod', models.TextField()),
                ('firstName', models.TextField()),
                ('lastName', models.TextField()),
                ('dateOfBirth', models.DateField()),
            ],
        ),
    ]
