# Generated by Django 3.2.8 on 2021-10-30 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospitalNumberName', models.TextField()),
                ('hospitalNumberRegex', models.TextField()),
                ('nationalPatientNumberName', models.TextField()),
                ('nationalPatientNumberRegex', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('hospitalNumber', models.TextField()),
                ('nationalNumber', models.TextField()),
                ('communicationMethod', models.TextField()),
                ('firstName', models.TextField()),
                ('lastName', models.TextField()),
                ('dateOfBirth', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('roleName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('firstName', models.TextField()),
                ('lastName', models.TextField()),
                ('userName', models.TextField()),
                ('passwordHash', models.TextField()),
                ('department', models.TextField()),
                ('lastAccess', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UserRolesBind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(through='api.UserRolesBind', to='api.Role'),
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('addedAt', models.DateTimeField()),
                ('description', models.TextField()),
                ('mediaUrls', models.TextField()),
                ('patient', models.ManyToManyField(to='api.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='DecisionPoint',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('addedAt', models.DateTimeField()),
                ('updatedAt', models.DateTimeField()),
                ('decisionType', models.TextField()),
                ('clinicHistory', models.TextField()),
                ('comorbidities', models.TextField()),
                ('clinician', models.ManyToManyField(to='api.User')),
                ('patient', models.ManyToManyField(to='api.Patient')),
            ],
        ),
    ]
