# Generated by Django 3.2.8 on 2021-10-22 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospitalNumberName', models.TextField()),
                ('hospitalNumberRegex', models.TextField()),
                ('nationalPatientNumberName', models.TextField()),
                ('nationalPatientNumberRegex', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DecisionPoint',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('patient', models.TextField()),
                ('addedAt', models.DateTimeField()),
                ('updatedAt', models.DateTimeField()),
                ('clinician', models.TextField()),
                ('decisionType', models.TextField()),
                ('clinicHistory', models.TextField()),
                ('comorbidities', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('patient', models.TextField()),
                ('addedAt', models.DateTimeField()),
                ('description', models.TextField()),
                ('mediaUrls', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('firstName', models.TextField()),
                ('lastName', models.TextField()),
                ('userName', models.TextField()),
                ('passwordHash', models.TextField()),
                ('department', models.TextField()),
                ('lastAccess', models.DateTimeField()),
                ('roles', models.TextField()),
            ],
        ),
    ]
