# Generated by Django 3.2.5 on 2021-08-16 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=80, null=True, verbose_name='First name')),
                ('lastName', models.CharField(max_length=80, null=True, verbose_name='Last name')),
                ('hospitalNumber', models.CharField(max_length=80, null=True, unique=True, verbose_name='Hospital number')),
                ('nationalPatientNumber', models.CharField(max_length=80, null=True, unique=True, verbose_name='NHS number')),
                ('DOB', models.DateField(verbose_name='Date of birth')),
            ],
            options={
                'verbose_name': 'Patient information',
                'ordering': ['lastName', 'DOB'],
            },
        ),
    ]
